Update useRD.yml

diff --git a/.github/workflows/useRD.yml b/.github/workflows/useRD.yml
--- a/.github/workflows/useRD.yml
+++ b/.github/workflows/useRD.yml
@@ -5,21 +5,24 @@ on:
 jobs:
   myEvent:
     runs-on: ubuntu-latest
+    if: "${{ !github.event.client_payload.prerelease }}"
     steps:
       #- run: echo ${{ github.event.client_payload.ref }} 
       #- run: echo ${{ fromJson(github.event.client_payload.github) }} 
       - name: check and format version string
         #if: echo "${{ github.event.client_payload.release }}" | awk -F"." '{print NF-1}'
         run: |
-             count=echo "${{ github.event.client_payload.release }}" | awk -F"." '{print NF-1}'
-             even="$(echo "${{ github.event.client_payload.release }}" | sed 's/$/.0/' | sed 's/v//' )"
-             odd="$(echo "${{ github.event.client_payload.release }}" | sed 's/v//')" 
-             if [[ $count -eq 2 ]]; then  version=$even; else  version=$odd; fi 
-             echo "$count"
-             echo "$even"
-             echo "$odd"
-             echo "$version"    
-             echo ::set-env name=VERSION_STRING::$version
+             client_payload="${{ github.event.client_payload.release }}"
+             version_number="$(echo "$client_payload" | sed 's/v//')" 
+             count="$(echo "$version_number" | awk -F"." '{print NF-1}')"
+             if [[ $count -eq 2 ]]; then 
+               version_number="$(echo "$version_number" | sed 's/$/.0/')"
+             fi
+             if [[ "$(echo "$version_number" | awk -F"." '{print NF-1}'" -ne 3 ]]; then
+               echo "The tag '$client_payload'  is invalid" 1>&2
+               exit 1
+             fi
+             echo "::set-env name=VERSION_STRING::$version_number"              
       - name: check version
         run: echo $VERSION_STRING 
 
